from enum import Enum


class DbStatus(str, Enum):
    RAW_DATA = "RAW_DATA"
    TRANSCRIPTION_IN_PROGRESS = "TRANSCRIPTION_IN_PROGRESS"
    TRANSCRIPTION_FAILED = "TRANSCRIPTION_FAILED"
    TRANSCRIPTION_COMPLETE = "TRANSCRIPTION_COMPLETE"
    CHUNKING_IN_PROGRESS = "CHUNKING_IN_PROGRESS"
    CHUNKING_COMPLETE = "CHUNKING_COMPLETE"
    EMBEDDING_IN_PROGRESS = "EMBEDDING_IN_PROGRESS"
    VECTOR_INGESTION_IN_PROGRESS = "VECTOR_INGESTION_IN_PROGRESS"
    VECTOR_INGESTION_COMPLETE = "VECTOR_INGESTION_COMPLETE"
    FAILED = "FAILED"
