KAFKA_BOOTSTRAP_SERVER = 'KAFKA_BOOTSTRAP_SERVER'

EMBEDDING_MODEL_NAME= 'BAAI/bge-large-en-v1.5'
SERVICE_PACKAGE = 'service.storage'
CHUNKED_DATA_TOPIC = 'chunked_data'
RAW_DATA_TOPIC = 'raw_data'
RAW_DATA_CONSUMER_GROUP = 'my-raw-data-consumer-group'

CHUNK_TOKEN_LIMIT = 400
CHUNK_TOKEN_OVERLAP = 50