from enum import Enum


class DbStatus(str, Enum):
    RAW_DATA = "RAW_DATA"
    CHUNKING_IN_PROGRESS = "CHUNKING_IN_PROGRESS"
    CHUNKING_COMPLETE = "CHUNKING_COMPLETE"
    RAW_CHUNKS = "RAW_CHUNKS"
    EMBEDDING_IN_PROGRESS = "EMBEDDING_IN_PROGRESS"
    VECTOR_INGESTION_IN_PROGRESS = "VECTOR_INGESTION_IN_PROGRESS"
    VECTOR_INGESTION_COMPLETE = "VECTOR_INGESTION_COMPLETE"
    FAILED = "FAILED"
