KAFKA_BOOTSTRAP_SERVER = 'KAFKA_BOOTSTRAP_SERVER'

EMBEDDING_MODEL_NAME= 'BAAI/bge-large-en-v1.5'
CHUNKED_DATA_TOPIC = 'chunked_data'
CHUNK_DATA_CONSUMER_GROUP = 'my-chunk-data-consumer-group'

CHUNK_TOKEN_LIMIT = 400
CHUNK_TOKEN_OVERLAP = 50

QDRANT_HOST_ENV = 'localhost'
QDRANT_HOST_PORT_ENV = '6333'